Feat create artifact repository and service
ABC-practica-2024/Backend pull request #29
Opened 2024-08-23 09:59 UTC by AlisaUrsu

2024-08-23 11:02 UTC, CalinescuFlorin requested changes
Pare ok, doar că ai un query invalid in repository

Cred că ar trebui să fie ceva de genul:
```
SELECT Artifacts.* FROM Artifacts 
INNER JOIN Section ON Artifacts.section_id = Section.id
INNER JOIN Site ON Section.site_id = Site.id
INNER JOIN Site_Archaeologist ON Site.id = Site_Archaeologist.site_id
WHERE Site.id = :siteId AND Site_Archaeologist.archaeologist_id = :archaeologistId;
```
Nu stiu dacă face ceea ce voiai, te rog să verifici și să corectezi.

2024-08-25 09:05 UTC, dunmer0 commented
> Pare ok, doar că ai un query invalid in repository
> 
> Cred că ar trebui să fie ceva de genul:
> 
> ```
> SELECT Artifacts.* FROM Artifacts 
> INNER JOIN Section ON Artifacts.section_id = Section.id
> INNER JOIN Site ON Section.site_id = Site.id
> INNER JOIN Site_Archaeologist ON Site.id = Site_Archaeologist.site_id
> WHERE Site.id = :siteId AND Site_Archaeologist.archaeologist_id = :archaeologistId;
> ```
> 
> Nu stiu dacă face ceea ce voiai, te rog să verifici și să corectezi.



In mod normal in Query scrii JPQL un fel de SQL dar interpretat de Java Persistence si 
pentru a putea scrie native SQL treubie adugat la urma nativeQuery = true. 
**e.g: `@Query(value = "some native SQL query", nativeQuery = true)`**

2024-08-27 11:04 UTC, AlisaUrsu commented
Am testat query-ul si functioneaza cum trebuie, doar i-am dat refactor putin sa arate mai clean. Am mai adaugat un validator pentru service-ul de Artifact si un exception class, inca o metoda care da retrieve la artefacte in functie de categorie (banuiesc ca o sa modificam category sa fie de tip enum in loc de string dupa ce o sa stim care sunt categoriile exacte). Am adaugat si teste pentru toate metodele din service.

2024-08-27 11:13 UTC, CalinescuFlorin approved these changes
looks good to me

2024-08-27 11:15 UTC, CalinescuFlorin commented
> categorie (banuiesc ca o sa modificam category sa fie de tip enum in loc de string dupa ce o sa stim care sunt categoriile exacte).

Gabi spunea ca nu vor fi categorii stabilite, ci vor fi introduse de user; momentan lasam asa, daca va fi cazul, facem tabela separata pt categorii

2024-08-27 11:15 UTC, merged